Blog/urls.py
from django.urls import path

from Blog import views

urlpatterns = [
    path('', views.RedirectToLatestPost.as_view(), name='latest_post'),
    path('create_post/', views.CreatePostView.as_view(), name='create_post'),
    path('drafts/', views.DraftsListView.as_view(), name='drafts'),
    path('edit_post/<slug:slug>', views.UpdatePostView.as_view(), name='edit_post'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('<slug:slug>/', views.PostView.as_view(), name='view_post'),
]

listen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from Home import views as views
from Home import actions as actions

from Project import views as projects_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),

    path('newsletter/', include('newsletter.urls')),
    path('surveys/', include(('Survey.urls', 'Survey'), namespace="Surveys")),
    path('blog/', include(('Blog.urls', "Blog"), namespace="Blog")),
    path('projects/', include(('Project.urls', "Project"), namespace="Project")),
    path('analysis/', include(('Analyze.urls', 'Analyze'), namespace='Analyze')),
    path('contacts/', include(('Contacts.urls', 'Contacts'), namespace='Contacts')),

    path('admin_tools/', views.AdminToolsView.as_view(), name="admin_tools"),

    path('accounts/login/', views.ListenLoginView.as_view(), name='account_login'),
    path('accounts/logout/', views.logout_request, name='account_logout'),
    path('accounts/signup/', views.ListenSignupView.as_view(), name='account_signup'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('', views.HomePageView.as_view()),
    path('contribute/', views.DonateView.as_view(), name='donate'),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('snapcode/', views.SnapcodeView.as_view(), name='snapcode'),
    path('news/', views.NewsView.as_view(), name='news'),

    path('newsletter_builder/<slug:slug>/', views.NewsletterBuilderView.as_view(), name='newsletter_builder'),
    path('read_newsletter/<slug:slug>/', views.ViewNewsletter.as_view(), name='view_newsletter'),
    path('newsletters/', views.NewsletterListView.as_view(), name='newsletter_list'),
    path('modify_newsletter/', actions.modify_newsletter, name='modify_newsletter'),

    path('submit_secret/', actions.submit_secret),
    path('set_permissions/', actions.set_permissions),
    path('quick_signup/', actions.quick_signup, name='quick_signup'),

    path('email_copy/', TemplateView.as_view(template_name='email_copy.html'), name='email'),


    path('about/', views.AboutView.as_view(), name="about"),
    path('start_survey/', views.SurveyLandingPage.as_view(), name="survey_landing"),
    path('home/', views.HomePageView.as_view(), name="home"),
    path('staff/', views.StaffPanelView.as_view(), name='staff'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.HomePageView.as_view()),

    path('sample/', projects_views.SampleProjectView.as_view(), name='sample'),
    path('<slug:slug>/', projects_views.ProjectView.as_view(), name='project'),
]

Blog/models.py
from datetime import datetime

from django.db import models
from django.urls import reverse_lazy

from django.utils.text import slugify
from ckeditor.fields import RichTextField

STATUS = (
    (0, "Draft"),
    (1, "Publish")
)


class Blog(models.Model):
    organization = models.ForeignKey("Home.Organization", on_delete=models.CASCADE)

    def __str__(self):
        return "Blog for " + self.organization.name


class Post(models.Model):
    title = models.CharField(max_length=256)
    slug = models.SlugField(unique=True)
    body = RichTextField(blank=True, null=True)
    author = models.CharField(max_length=256)
    status = models.IntegerField(choices=STATUS, default=0)
    published_on = models.DateField(null=True, blank=True)
    project = models.ForeignKey('Project.Project', on_delete=models.SET_NULL, null=True, blank=True)
    blog = models.ForeignKey(Blog, on_delete=models.PROTECT)

    class Meta:
        ordering = ['published_on']

    def get_absolute_url(self):
        return reverse_lazy("Blog:view_post", args=[self.slug])

    def save(self, *args, **kwargs):
        # TODO: This needs to be set to properly find the correct Blog
        self.blog = Blog.objects.all().first()
        self.slug = slugify(self.title)
        super(Post, self).save(*args, **kwargs)

    def publish(self):
        self.status = 1
        self.published_on = datetime.now().date()
        self.save()

    @property
    def is_published(self):
        return True if self.status == 1 else False

Home/models.py
from django.db import models

from django.contrib.auth.models import PermissionsMixin
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager
from django.db.models.signals import post_save
from django.contrib.auth.signals import user_logged_in
from django.dispatch import receiver

from Survey.models import Respondent, Questionnaire
from Analyze.models import Researcher

from .choices import LOCATIONS
from .mails import WelcomeEmail


class Language(models.Model):
    label = models.CharField(max_length=24)
    code = models.CharField(max_length=7)

    def __str__(self):
        return self.label


class Organization(models.Model):
    name = models.CharField(max_length=255)
    host = models.CharField(max_length=255)
    languages = models.ManyToManyField(Language)
    city = models.CharField(max_length=255)

    def __str__(self):
        return self.name


class ListenUserManager(BaseUserManager):

    def create_user(self, username, password=None):

        user = self.model(
            username=username,
        )
        user.set_password(password)
        user.organization = Organization.objects.all().first()
        user.save(using=self._db)
        return user

    def create_superuser(self, username, password):
        """
        Creates and saves a superuser with the given email, date of
        birth and password.
        """
        user = self.create_user(
            username,
            password=password,
        )
        user.is_superuser = True
        user.is_admin = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class ListenUser(AbstractBaseUser, PermissionsMixin):
    username = models.CharField(max_length=255, unique=True)
    organization = models.ForeignKey(Organization, on_delete=models.PROTECT, blank=True, null=True)
    email = models.EmailField(verbose_name='email address', max_length=255, null=True, blank=True)
    phone_number = models.CharField(max_length=24, null=True, blank=True)
    allows_contact_email = models.BooleanField(default=False)
    allows_contact_sms = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_admin = models.BooleanField(default=False)
    is_staff = models.BooleanField(default=False)
    login_is_email = models.BooleanField(default=True)
    site_language = models.ForeignKey(Language, null=True, blank=True, on_delete=models.SET_NULL, related_name='users_site')
    survey_language = models.ForeignKey(Language, null=True, blank=True, on_delete=models.SET_NULL, related_name='users_survey')

    objects = ListenUserManager()

    USERNAME_FIELD = 'username'

    def save(self, **kwargs):
        self.organization = Organization.objects.get(name="Listen To Shafter")
        super(ListenUser, self).save(**kwargs)

    @property
    def formatted_phone_number(self):
        raw_number = self.phone_number
        area_code = None
        if len(raw_number) == 10:
            area_code = "({})".format(raw_number[:3])
            raw_number = raw_number[3:]
        if len(raw_number) == 7:
            area_code = area_code if area_code else "(661)"
            output = "{} {}-{}".format(area_code, raw_number[:3], raw_number[3:])
        else:
            output = ""
        return output

    def get_full_name(self):
        return "Fellow Shafter Person"

    def is_researcher(self):
        return True if Researcher.objects.filter(user=self).exists() else False


class Whisper(models.Model):
    data = models.CharField(max_length=40)

    def __str__(self):
        return self.data


class Newsletter(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    date = models.DateField()
    intro = models.TextField()

    def __str__(self):
        return self.date


class Bullet(models.Model):
    newsletter = models.ForeignKey(Newsletter, on_delete=models.CASCADE)
    section = models.IntegerField()
    text = models.TextField()
    order = models.IntegerField()

    def __str__(self):
        return "{}, {} ({})".format(self.newsletter, self.section, self.order)

    class Meta:
        ordering = ['order']


class Copy(models.Model):
    organization = models.ForeignKey(Organization, on_delete=models.CASCADE)
    header = models.CharField(max_length=87, blank=True, null=True)
    text = models.TextField()
    location = models.IntegerField(choices=LOCATIONS, null=True, blank=True)
    order = models.IntegerField(blank=True, null=True)
    fa_icon = models.CharField(max_length=54, blank=True, null=True)
    event = models.ForeignKey('Project.Event', null=True, on_delete=models.SET_NULL)

    class Meta:
        ordering = ["order"]

    def __str__(self):
        return "{} ({})".format(self.get_location_display(), self.order)


class TranslatedText(models.Model):
    language = models.ForeignKey(Language, on_delete=models.PROTECT)
    text = models.TextField()
    header = models.CharField(max_length=87, blank=True, null=True)
    newsletter = models.ForeignKey(Newsletter, blank=True, null=True, on_delete=models.CASCADE)
    bullet = models.ForeignKey(Bullet, blank=True, null=True, on_delete=models.CASCADE)
    copy = models.ForeignKey(Copy, blank=True, null=True, on_delete=models.CASCADE)

    def __str__(self):
        if self.newsletter:
            output = self.newsletter.date
        elif self.bullet:
            output = "{} ({})".format(self.bullet.newsletter.date, self.bullet.section)
        else:
            output = "{} ({})".format(self.copy.get_location_display(), self.copy.order)

        return output


@receiver(post_save, sender=ListenUser)
def process_user(sender, instance, created, **kwargs):
    if created:

        # Create Respondent Object
        respondent = Respondent.objects.create(user=instance, organization=instance.organization)

        # Set Contact Info
        username = instance.username
        if "@" in username:
            instance.email = username
            instance.save()
        elif username.isdigit():
            if len(username) == 11 and username[0] == "1":
                instance.phone_number = username[1:]
            elif len(username) == 10:
                instance.phone_number = username
            elif len(username) == 7:
                instance.phone_number = "661" + username
            instance.save()

        # Add to Eligible Surveys
        surveys = Questionnaire.objects.filter(
            organization=instance.organization,
            login_is_required=True,
            survey_code__isnull=False
        )
        respondent.eligible_for.set(surveys)

        # Send a welcome email
        if instance.email:
            msg = WelcomeEmail({
                'site_name': "Listen To Shafter",
                'site_url': "http://www.listentoshafter.org"})
            msg.send([instance.email])


@receiver(user_logged_in)
def test(request, user, *args, **kwargs):
    try:
        if request.session.get('language') == 1:
            user.site_language = user.survey_language = Language.objects.get(id=1)
            user.save()
    except AttributeError:
        pass

Blog/forms.py
from django import forms

from .models import Post


class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = ['title', 'author', 'project', 'body']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['title'].widget.attrs.update({'class': 'border-b w-1/3'})
        self.fields['author'].widget.attrs.update({'class': 'border-b w-1/3'})
        self.fields['project'].widget.attrs.update({'class': 'border-b w-1/3'})

Blog/views.py
from django.views.generic import CreateView, DetailView, RedirectView, UpdateView, ListView, TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin

from Home.views import LanguageMixin
from Blog.forms import PostForm
from Blog.models import Post


class CreatePostView(LanguageMixin, LoginRequiredMixin, UserPassesTestMixin, CreateView):
    model = Post
    form_class = PostForm
    template_name = "create_post.html"

    def test_func(self):
        return self.request.user.is_staff


class UpdatePostView(LanguageMixin, LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Post
    form_class = PostForm
    template_name = "create_post.html"

    def test_func(self):
        return self.request.user.is_staff


class DraftsListView(LoginRequiredMixin, UserPassesTestMixin, ListView):
    template_name = 'drafts.html'
    model = Post

    def test_func(self):
        return self.request.user.is_staff


class PostView(DetailView):
    template_name = "view_post.html"
    model = Post

    @property
    def is_preview(self):
        return True if self.get_object().status == 0 else False

    def is_editable(self):
        return self.request.user.is_staff if not self.request.user.is_anonymous else False

    def post(self, request, *args, **kwargs):
        publish_requested = True if request.POST.get('publish') == "true" else False
        if publish_requested and self.is_preview and self.request.user.is_staff:
            self.get_object().publish()
            return self.get(self, request, *args, **kwargs)
        else:
            return self.get(self, request, *args, **kwargs)


class RedirectToLatestPost(RedirectView):
    pattern_name = 'Blog:view_post'

    def get_redirect_url(self, *args, **kwargs):
        args = [Post.objects.filter(status__gt=0).latest('published_on').slug]
        return super().get_redirect_url(*args, **kwargs)


class IndexView(TemplateView):
    template_name = 'directory.html'

    def get_posts(self):
        return Post.objects.filter(blog__organization=1).order_by('-published_on')
        
    def posts_by_year(self):
        output = {}
        for post in self.get_posts():
            if post.published_on:
                year = post.published_on.year
                data = {'slug': post.slug, 'title': post.title}
                if year in output:
                    output[year].append(data)
                else:
                    output[year] = [data]
        return output

    def posts_by_project(self):
        output = {}
        for post in self.get_posts():
            project = post.project.name if post.project else "Various"
            data = {'slug': post.slug, 'title': post.title}
            if project in output:
                output[project].append(data)
            else:
                output[project] = [data]
        return output

Blog/templates/create_post.html
{% extends 'siteframe_static.html' %}
{% load static %}
{% load home_tags %}

{% block extra_css %}
    <link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'css/form-validation.css' %}">
{% endblock %}

{% block content %}
<div class="flex flex-row">

    <div class="md:w-1/3 bg-white flex flex-col gap-4"></div>

    <div class="bg-white w-full border p-6" style="min-height: 100vh;">

    {% if message %}
    {{ message }}
    {% endif %}
    <form class="flex flex-col gap-6" method="POST" action="">

        {% csrf_token %}
        {{ form.media }}

        <div class="form-title-row">
            <h1 class="text-2xl">Create Post</h1>
        </div>

        <p>{{ form.non_field_errors }}</p>

        {% for field in form %}
        <div class="flex flex-col">
            <label class="text-lg" for="{{ form.field.id_for_label}}">
                <span>{{ field.label }}:</span>
            </label>
            {{ field.errors }}
            <div class="pt-2">{{ field }}</div>
        </div>
        {% endfor %}

        <div class="flex flex-row justify-end">
            <input class="px-3 py-2 bg-green-600 text-white cursor-pointer hover:bg-green-700" type="submit" />
        </div>
    </form>

    </div>

    <div class="md:w-1/3 bg-white flex flex-col gap-4"></div>
</div>
{% endblock %}

{% block extra_js %}
<script src="https://cdn.quilljs.com/1.3.6/quill.js"></script>

<!-- Initialize Quill editor -->
<script>
  let quill = new Quill('#id_text', {

  });
</script>

{% endblock %}

Blog/templates/directory.html
{% extends 'siteframe_static.html' %}
{% load generic %}

{% block content %}
<div class="flex flex-row" style="min-height: 100vh;">
    <div class="md:w-1/3 bg-white bg-opacity-75 flex flex-col gap-4"></div>

    <div class="bg-white p-5 md:p-8 w-full">
        <div class="my-4 text-xl flex flex-row justify-around">
            <h2 class="md:text-2xl underline">Listen To Shafter Blog Posts</h2>
        </div>

        <div class="flex flex-row gap-4 justify-center mt-9 mb-3 md:justify-start">
            <div onclick="setByDate()" class="p-2 border cursor-pointer select-none bg-gray-200">By Date</div>
            <div onclick="setByProject()" class="p-2 border cursor-pointer select-none hover:bg-gray-100 ">By Project</div>
        </div>

        <div id="byDate">
        {% for year, batch in view.posts_by_year.items  %}
            <div class="mt-10 mb-2 border-b pb-2 text-lg font-bold">{{ year }}</div>
            <div class="flex flex-col gap-4 flex-wrap">
            {% for item in batch %}
                <div class="text-lg">
                    <a href="{% url 'Blog:view_post' item|get_from_dict:'slug'  %}" class="text-blue-400">
                        {{ item|get_from_dict:'title' }}
                    </a>
                </div>
            {% endfor %}
            </div>
        {% endfor %}
        </div>

        <div id="byProject" style="display: none;">
        {% for project, batch in view.posts_by_project.items  %}
            <div class="mt-10 mb-2 border-b pb-2 text-lg font-bold">{{ project }}</div>
            <div class="flex flex-col gap-4 flex-wrap">
            {% for item in batch %}
                <div class="text-lg">
                    <a href="{% url 'Blog:view_post' item|get_from_dict:'slug'  %}" class="text-blue-400">
                        {{ item|get_from_dict:'title' }}
                    </a>
                </div>
            {% endfor %}
            </div>
        {% endfor %}
        </div>

    </div>



    <div class="md:w-1/3 bg-white bg-opacity-75"></div>
</div>
{% endblock %}

{% block extra_js %}

<script>

function setByProject() {
    document.getElementById('byProject').style.display = 'block'
    document.getElementById('byDate').style.display = 'none'
}

function setByDate() {
    document.getElementById('byDate').style.display = 'block'
    document.getElementById('byProject').style.display = 'none'
}

</script>

{% endblock %}

Blog/templates/drafts.html
{% extends 'siteframe_static.html' %}
{% load static %}

{% block extra_css %}
    <link href="{% static 'css/blog.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="bg-white h-screen select-none flex flex-row gap-6">

        <div class="w-1/3"></div>

        <div class="flex flex-col gap-4 w-full pt-6">
            <div class="row actions my-4">
                <a href="{% url "Blog:create_post" %}" class="btn btn-white btn-small">Create New</a>
            </div>
            <h1 class="text-2xl mb-2 border-b">Drafts</h1>
            <div class="row">
                <ul id="drafts">
                    {% for draft in object_list %}
                        {% if not draft.is_published %}
                        <li style="list-style: none">
                            <a class="text-blue-600" href="{% url "Blog:view_post" draft.slug %}">{{ draft.title }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}
                </ul>
            </div>

            <h1 class="text-2xl mb-2 border-b">Published</h1>

            <ul id="drafts">
                {% for draft in object_list %}
                    {% if draft.is_published %}
                    <li style="list-style: none">
                        <a class="text-blue-600" href="{% url "Blog:view_post" draft.slug %}">{{ draft.title }}</a>
                    </li>
                    {% endif %}
                {% endfor %}
            </ul>
        </div>
        <div class="w-1/3"></div>
    </div>
{% endblock %}

Blog/templates/view_post.html
{% extends 'siteframe_static.html' %}
{% load static %}

{% block content %}
<div class="flex flex-row" style="min-height: 100vh;">
    <div class="md:w-1/3 bg-white bg-opacity-75 flex flex-col gap-4"></div>

    <div class="bg-white p-5 md:p-8 w-full">
        <div class="text-2xl md:text-3xl my-3">
            <h1 id="title">{{ object.title }}</h1>
        </div>
        <div class="row mb-4 text-gray-500">
            <h5 class="post-detail" id="author">{{ object.author }} | {% if view.is_preview %}Preview Mode{% else %}{{ object.published_on }}{% endif %}</h5>
        </div>
        <div class="flex flex-row gap-4 mb-4">
        {% if view.is_editable %}
            {% if view.is_preview %}
                <a href="#" class="border p-2" onclick="document.forms['publishForm'].submit(); return false;">Publish</a>
                <a href="{% url "Blog:edit_post" object.slug %}" class="border p-2">Edit</a>
            {% else %}
                <a href="{% url "Blog:edit_post" object.slug %}" class="border p-2">Open in Editor</a>
            {% endif %}
        {% endif %}
        </div>
        <form id="publishForm" method="post" style="display: none">
          {% csrf_token %}
          <input type="hidden" name="publish" value="true">
        </form>
        <div class="border-t pt-4 text-2xl">
            <p>{% autoescape off %}{{ object.body }}{% endautoescape %}</p>
        </div>
    </div>
    <div class="md:w-1/3 bg-white bg-opacity-75 flex flex-col gap-4"></div>
</div>
<form id="publishForm" method="post" name="publishForm" style="display: none">
{% csrf_token %}
<input type="hidden" name="publish" value="true">
</form>
{% endblock %}