Blog/urls.py
from django.urls import path

from Blog import views

urlpatterns = [
    path('', views.RedirectToLatestPost.as_view(), name='latest_post'),
    path('create_post/', views.CreatePostView.as_view(), name='create_post'),
    path('drafts/', views.DraftsListView.as_view(), name='drafts'),
    path('edit_post/<slug:slug>', views.UpdatePostView.as_view(), name='edit_post'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('<slug:slug>/', views.PostView.as_view(), name='view_post'),
]

Contacts/urls.py
from django.urls import path

from Contacts import views, actions

urlpatterns = [
    # Views
    path('', views.ContactsView.as_view(), name='contacts'),
    path('portal/', views.CommunityPortalView.as_view(), name="portal"),

    # Actions
    path('manage_contact/', actions.manage_contact, name='manage_contact'),
    path('search_people/', actions.search_people, name='search_people')
]

Project/urls.py
from django.urls import path

from Project import actions

urlpatterns = [
    path('add_project/', actions.add_project, name='add_project'),
    path('get_districts', actions.get_districts, name="get_districts"),
    path('manage_district/', actions.manage_district, name='manage_district')
]

listen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from Home import views as views
from Home import actions as actions

from Project import views as projects_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),

    path('newsletter/', include('newsletter.urls')),
    path('surveys/', include(('Survey.urls', 'Survey'), namespace="Surveys")),
    path('blog/', include(('Blog.urls', "Blog"), namespace="Blog")),
    path('projects/', include(('Project.urls', "Project"), namespace="Project")),
    path('analysis/', include(('Analyze.urls', 'Analyze'), namespace='Analyze')),
    path('contacts/', include(('Contacts.urls', 'Contacts'), namespace='Contacts')),

    path('admin_tools/', views.AdminToolsView.as_view(), name="admin_tools"),

    path('accounts/login/', views.ListenLoginView.as_view(), name='account_login'),
    path('accounts/logout/', views.logout_request, name='account_logout'),
    path('accounts/signup/', views.ListenSignupView.as_view(), name='account_signup'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('', views.HomePageView.as_view()),
    path('contribute/', views.DonateView.as_view(), name='donate'),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('snapcode/', views.SnapcodeView.as_view(), name='snapcode'),
    path('news/', views.NewsView.as_view(), name='news'),

    path('newsletter_builder/<slug:slug>/', views.NewsletterBuilderView.as_view(), name='newsletter_builder'),
    path('read_newsletter/<slug:slug>/', views.ViewNewsletter.as_view(), name='view_newsletter'),
    path('newsletters/', views.NewsletterListView.as_view(), name='newsletter_list'),
    path('modify_newsletter/', actions.modify_newsletter, name='modify_newsletter'),

    path('submit_secret/', actions.submit_secret),
    path('set_permissions/', actions.set_permissions),
    path('quick_signup/', actions.quick_signup, name='quick_signup'),

    path('email_copy/', TemplateView.as_view(template_name='email_copy.html'), name='email'),


    path('about/', views.AboutView.as_view(), name="about"),
    path('start_survey/', views.SurveyLandingPage.as_view(), name="survey_landing"),
    path('home/', views.HomePageView.as_view(), name="home"),
    path('staff/', views.StaffPanelView.as_view(), name='staff'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.HomePageView.as_view()),

    path('sample/', projects_views.SampleProjectView.as_view(), name='sample'),
    path('<slug:slug>/', projects_views.ProjectView.as_view(), name='project'),
]

Contacts/models.py
from django.db import models
from .choices import INTEREST_LEVELS, RESPONSES

from .managers import PersonSearchManager


class Quality(models.Model):
    label = models.CharField(max_length=128)


class Issue(models.Model):
    label = models.CharField(max_length=128)


class Tag(models.Model):
    label = models.CharField(max_length=128)


class Concern(models.Model):
    label = models.CharField(max_length=128)
    intensity = models.IntegerField(choices=INTEREST_LEVELS)


class Residence(models.Model):
    district = models.ForeignKey("Project.District", on_delete=models.SET_NULL, blank=True, null=True)
    address = models.CharField(max_length=128)
    city = models.CharField(max_length=64)
    state = models.CharField(max_length=24)
    postal_code = models.CharField(max_length=24)


class Person(models.Model):
    name = models.CharField(max_length=64)
    email = models.EmailField(null=True, blank=True)
    phone = models.CharField(max_length=24, null=True, blank=True)
    residence = models.ForeignKey(Residence, null=True, blank=True, on_delete=models.SET_NULL)
    district = models.ForeignKey("Project.District", on_delete=models.SET_NULL, blank=True, null=True)
    projects = models.ManyToManyField("Project.Project")

    objects = PersonSearchManager()


class Log(models.Model):
    user = models.ForeignKey('Home.ListenUser', on_delete=models.PROTECT)
    person = models.ForeignKey(Person, on_delete=models.CASCADE)
    notes = models.TextField(blank=True)
    hours = models.IntegerField(blank=True, null=True)
    dollars = models.IntegerField(blank=True, null=True)
    project = models.ForeignKey("Project.Project", blank=True, null=True, on_delete=models.PROTECT)
    event = models.ForeignKey("Project.Event", blank=True, null=True, on_delete=models.PROTECT)
    concern = models.ForeignKey(Concern, models.PROTECT, blank=True, null=True)
    quality = models.ForeignKey(Quality, models.PROTECT, blank=True, null=True)
    old_address = models.ForeignKey(Residence, on_delete=models.PROTECT, null=True, blank=True, related_name="address_change_from")
    new_address = models.ForeignKey(Residence, on_delete=models.PROTECT, null=True, blank=True, related_name="address_change_to")
    response = models.IntegerField(choices=RESPONSES, blank=True, null=True)

Contacts/views.py
from django.views.generic import TemplateView
from django.contrib.auth.mixins import UserPassesTestMixin

from Home.mixins import LanguageMixin
from Project.models import Project


class ContactsView(LanguageMixin, TemplateView, UserPassesTestMixin):
    template_name = "contacts.html"
    app_name = 'contacts'

    def test_func(self):
        return self.request.user.is_admin

    def projects(self):
        return Project.objects.all()


class CommunityPortalView(LanguageMixin, TemplateView, UserPassesTestMixin):
    template_name = "portal.html"

    def test_func(self):
        return self.request.user.is_admin

    def projects(self):
        return Project.objects.all()

Contacts/templates/contact_card.html
<div class="contact-frame">
    <div class="row">
        <div class="col-sm-12">
            <h5 class="contact-name">{{ object.name }}</h5><br>
        </div>
    </div>
    <div class="row" style="margin-bottom: 30px;">
        <div class="col-sm-12">
            <h5 class="section-title contact">Contact Info</h5>
            <span class="contact-title">Ph: </span><span class="contact-info">{{ object.phone }}</span>
            <span class="contact-title"> Email: </span><span class="contact-info">{{ object.email }}</span>
            <span class="contact-title">Address: </span><span class="contact-info">{{ object.address }}</span>
        </div>
    </div>
    <div class="row">
        <div class="col-sm-12 col-md-4">
            <h5 class="section-title contact">Priorites</h5>
            <span class="contact-info">Food Security</span><br>
            <span class="contact-info">Education</span><br>
            <span class="contact-info">Environment</span>
        </div>
        <div class="col-sm-12 col-md-4">
            <div class="contact-details">
                <h5 class="section-title contact">Relations</h5>
                <p class="contact-detail">Sister to Rafael Gomez</p>
                <p class="contact-detail">Daughter of Cristina Gomez</p>
            </div>
        </div>
        <div class="col-sm-12 col-md-4">
            <div class="contact-details">
                <h5 class="section-title contact">Activity</h5>
                <p class="contact-detail">Attended Food Security Planning Event C</p>
                <p class="contact-detail">Responded to Food Security Survey</p>
            </div>
        </div>
    </div>
    <div class="row" id="contactAction">
        <a href="#" class="btn btn-dark btn-md" id="emailContact" data-contact="">Email Contact</a>
        <a href="#" class="btn btn-dark btn-md" id="smsContact" data-contact="">SMS Contact</a>
    </div>
</div>

Contacts/templates/contacts.html
{% extends 'vueframe.html' %}
{% load render_bundle from webpack_loader %}
{% render_bundle 'chunk-vendors' %}
{% render_bundle 'contacts' %}

{% block pageTitle %}Contacts{% endblock %}

{% block appName %}contactsApp{% endblock %}


{% block rootData %}
<script>
    rootData['urlpaths']['manageContact'] = "{% url 'Contacts:manage_contact' %}"
    rootData['urlpaths']['getDistricts'] = "{% url 'Project:get_districts' %}"
    rootData['urlpaths']['manageDistrict'] = "{% url 'Project:manage_district' %}"
</script>
{% endblock %}

Contacts/templates/portal.html
{% extends 'siteframe.html' %}
{% load static %}
{% load home_tags %}

{% block extra_css %}
     <link href="{% static 'css/community.css' %}" rel="stylesheet">
{% endblock %}

{#{% block remove-header %}{% endblock %}#}
{% block remove-top %}{% endblock %}

{% block main %}
    <div class="row">
        <div class="col-sm-12 text-center" style="padding: 0px;">
            <h3 id="pageTitle">Community Network Portal</h3>
        </div>
    </div>

    <div class="row" style="margin-top: 27px;">
        <!-- Filters -->
        <div class="col-sm-12 col-md-3 filter-frame">
            <h5 class="section-title" style="margin-top: 12px;">Filter Contacts:</h5>
            <label class="filter-label" for="projectFilter">By Project</label>
            <select name="projects" id="projectFilter" class="form-control">
                <option selected value="">Select Project</option>
                {% for project in view.projects %}
                <option value="{{ project.id }}">{{ project.name }}</option>
                {% endfor %}
            </select>
            <label class="filter-label" for="neighborhoodFilter">By Neighborhood</label>
            <select name="projects" id="neighborhoodFilter" class="form-control">
                <option selected value="">Select Neighborhoods</option>
                <option value="1">Barrio Norte</option>
                <option value="2">Tree Streets</option>
                <option value="3">Rodriguez Park</option>
            </select>
            <label class="filter-label" for="priorityFilter">By Priority</label>
            <select name="projects" id="priorityFilter" class="form-control">
                <option selected value="">Select Priority</option>
                <option value="1">Public Safety</option>
                <option value="2">Environment</option>
                <option value="3">Food Security</option>
            </select>
        </div>
        <!-- Summary -->
        <div class="col-sm-12 col-md-9">
            <div id="actionRow">
                <a href="#" id="bulkAdd" class="btn btn-dark float-right">Bulk Add</a>
                <a href="#" id="neighborhoods" class="btn btn-dark float-right">Neighborhoods</a>
            </div>
            <div class="summary">
                <div class="row">
                    <div class="col-sm-12 col-md-6">
                        <h5 class="section-title">This Month</h5>
                        <ol>
                            <li>James Robinson</li>
                            <li>Jack Taylor</li>
                            <li>Mark Rodriguez</li>
                            <li>Patricia Neufeld</li>
                            <li>Pat Mackenzie</li>
                        </ol>
                    </div>
                    <div class="col-sm-12 col-md-6">
                        <h5 class="section-title">This Year</h5>
                        <ol>
                            <li>James Robinson</li>
                            <li>Jack Taylor</li>
                            <li>Mark Rodriguez</li>
                            <li>Patricia Neufeld</li>
                            <li>Pat Mackenzie</li>
                        </ol>
                    </div>
                    <a href="#" id="viewAll" class="btn btn-dark col-sm-12">View All</a>
                </div>
            </div>
        </div>
    </div>
    <hr class="page-divide">
    <div class="row contacts">
        <!-- Manage Contact -->
        <div class="col-sm-12 col-md-4" id="search_frame">
            <h5 class="section-title search">Search/Add</h5>
            <form id="addPerson">
               <div class="form-group col-md-10">
                  <label class="filter-label" for="name">Name</label>
                  <input type="text" name="name" class="form-control" id="name">
               </div>
                <div class="form-group col-md-10">
                  <label class="filter-label" for="name">Phone</label>
                  <input type="text" name="phone" class="form-control" id="phone">
               </div>
                <div class="form-group col-md-10">
                  <label class="filter-label" for="name">Email</label>
                  <input type="email" name="email" class="form-control" id="email">
               </div>
                <div class="form-group col-md-10">
                  <label class="filter-label" for="name">Address</label>
                  <input type="text" name="address" class="form-control" id="address">
               </div>
               <div class="form-group col-md-10">
                  <label class="survey-label" for="project">Link to Project</label>
                  <select name="project" id="project" class="form-control">
                    <option selected value="">Select Projects</option>
                    {% for project in view.projects %}
                    <option value="{{ project.id }}">{{ project.name }}</option>
                    {% endfor %}
                  </select>
               </div>
                <a href="#" class="btn btn-dark submit" id="contactSubmit" data-contact="">Add Contact</a>
            </form>
        </div>

        <!-- Filtered Contacts -->
        <div class="col-sm-12 col-md-8" id="contactFilterResults">
            <p>No Matching Contacts</p>
        </div>
    </div>

{% endblock main %}
{% block override_footer %}{% endblock %}
{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/contacts/portal.js' %}"></script>
{% endblock extra_js %}