Analyze/urls.py
from django.urls import path

from Analyze import views, actions

urlpatterns = [
    path('evaluate/select_survey', views.SurveySelectionView.as_view(), name='select_survey'),
    path('evaluate/<int:survey_id>', views.QuestionSelectionView.as_view(), name='select_question'),
    path('evaluate/<int:survey_id>/<int:question_id>', views.EvaluationView.as_view(), name='evaluate'),

    path('add_code/', actions.create_code),
    path('add_note/', actions.create_note),
    path('add_comment/', actions.add_comment),
    path('add_researcher/', actions.add_researcher),
    path('delete_tag/', actions.delete_tag),
    path('merge_tags/', actions.merge_tags),
    path('select_discussion/', actions.select_discussion),
    path('submit_evaluation/', actions.save_evaluation),
    path('records/user/<slug:slug>', views.UserActivityView.as_view(), name='user-records'),
    path('records/answer/<slug:slug>', views.AnswerActivityView.as_view(), name='answer-records'),
    path('records/', views.GeneralActivityView.as_view(), name='general-records'),
]

Blog/urls.py
from django.urls import path

from Blog import views

urlpatterns = [
    path('', views.RedirectToLatestPost.as_view(), name='latest_post'),
    path('create_post/', views.CreatePostView.as_view(), name='create_post'),
    path('drafts/', views.DraftsListView.as_view(), name='drafts'),
    path('edit_post/<slug:slug>', views.UpdatePostView.as_view(), name='edit_post'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('<slug:slug>/', views.PostView.as_view(), name='view_post'),
]

listen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from Home import views as views
from Home import actions as actions

from Project import views as projects_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),

    path('newsletter/', include('newsletter.urls')),
    path('surveys/', include(('Survey.urls', 'Survey'), namespace="Surveys")),
    path('blog/', include(('Blog.urls', "Blog"), namespace="Blog")),
    path('projects/', include(('Project.urls', "Project"), namespace="Project")),
    path('analysis/', include(('Analyze.urls', 'Analyze'), namespace='Analyze')),
    path('contacts/', include(('Contacts.urls', 'Contacts'), namespace='Contacts')),

    path('admin_tools/', views.AdminToolsView.as_view(), name="admin_tools"),

    path('accounts/login/', views.ListenLoginView.as_view(), name='account_login'),
    path('accounts/logout/', views.logout_request, name='account_logout'),
    path('accounts/signup/', views.ListenSignupView.as_view(), name='account_signup'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('', views.HomePageView.as_view()),
    path('contribute/', views.DonateView.as_view(), name='donate'),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('snapcode/', views.SnapcodeView.as_view(), name='snapcode'),
    path('news/', views.NewsView.as_view(), name='news'),

    path('newsletter_builder/<slug:slug>/', views.NewsletterBuilderView.as_view(), name='newsletter_builder'),
    path('read_newsletter/<slug:slug>/', views.ViewNewsletter.as_view(), name='view_newsletter'),
    path('newsletters/', views.NewsletterListView.as_view(), name='newsletter_list'),
    path('modify_newsletter/', actions.modify_newsletter, name='modify_newsletter'),

    path('submit_secret/', actions.submit_secret),
    path('set_permissions/', actions.set_permissions),
    path('quick_signup/', actions.quick_signup, name='quick_signup'),

    path('email_copy/', TemplateView.as_view(template_name='email_copy.html'), name='email'),


    path('about/', views.AboutView.as_view(), name="about"),
    path('start_survey/', views.SurveyLandingPage.as_view(), name="survey_landing"),
    path('home/', views.HomePageView.as_view(), name="home"),
    path('staff/', views.StaffPanelView.as_view(), name='staff'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.HomePageView.as_view()),

    path('sample/', projects_views.SampleProjectView.as_view(), name='sample'),
    path('<slug:slug>/', projects_views.ProjectView.as_view(), name='project'),
]

Analyze/models.py
from datetime import timedelta, datetime
from django.db import models
from .managers import ResolutionManager


RESEARCHER_WEIGHTS = {
    1 : 3,
    2 : 14,
    3 : 23,
    4 : 25,
    5 : 26.7,
    6 : 200 # Master Account
}

RESEARCHER_THRESHOLDS = {
    2: 25,
    3: 100,
    4: 500,
    5: 1000,
    6: 10000, # Safety Value (Not actually included in loop).
}


class Researcher(models.Model):
    """ User with a role of researcher """
    user = models.ForeignKey('Home.ListenUser', on_delete=models.CASCADE)
    name = models.CharField(max_length=48, default='anonymous')
    eligible_for = models.ManyToManyField('Survey.Questionnaire')
    base_competency = models.IntegerField(default=1) # Initial competency status. Should be 1-5.

    def correct_evaluations(self):
        return self.evaluation_set.filter(correct=True)

    def incorrect_evaluations(self):
        return self.evaluation_set.filter(correct=False)

    def total_evaluations(self):
        return self.evaluation_set.all().count()

    def total_rated_evaluation(self):
        return self.correct_evaluations() + self.incorrect_evaluations()

    def calculate_recent_success_ratio(self, qty):
        recent_set = self.evaluation_set.filter(correct__isnull=False).order_by('-id')[:qty]
        if recent_set:
            correct_in_recent_set = self.evaluation_set.filter(id__in=recent_set, correct=True)
            result = correct_in_recent_set.count() / len(recent_set)
        else:
            result = 0
        return result

    def calculate_current_competency(self):
        evaluated_competency = base_competency = self.base_competency
        for x in range (5, 1, -1):
            threshold = RESEARCHER_THRESHOLDS[x]
            if self.total_evaluations() >= threshold and self.calculate_recent_success_ratio(threshold) >= .9:
                evaluated_competency = x if x >= base_competency else base_competency
        return evaluated_competency

    def current_weight(self):
        return RESEARCHER_WEIGHTS[self.calculate_current_competency()]


class Datum(models.Model):
    """ An option that a user has associated with a question. """
    question = models.ForeignKey('Survey.Question', on_delete=models.CASCADE)
    label = models.CharField(max_length=64)
    upper = models.CharField(max_length=64)


class Note(models.Model):
    """ Further Information related to a Datum. """
    question = models.ForeignKey('Survey.Question', on_delete=models.CASCADE)
    label = models.CharField(max_length=64)
    upper = models.CharField(max_length=64)


class Evaluation(models.Model):
    """ Coordinating object linking researchers to responses that they have evaluated and assigning a weight value based
        on the researcher's rating at the time of evaluation. """
    researcher = models.ForeignKey(Researcher, on_delete=models.CASCADE)
    response = models.ForeignKey('Survey.TextAnswer', on_delete=models.CASCADE, related_name='evaluations')
    datum = models.ManyToManyField(Datum, related_name='evaluations')
    # data_string = models.CharField(max_length=64)
    correct = models.BooleanField(blank=True, null=True)
    notes = models.ManyToManyField(Note, related_name='evaluations')
    weight = models.IntegerField(blank=True, null=True)
    timestamp = models.DateTimeField()
    skipped = models.BooleanField(default=False)


class Resolution(models.Model):
    """ An independent record recording an accepted evaluation based on weight-appreciative researcher consensus. """
    response = models.ForeignKey('Survey.TextAnswer', on_delete=models.CASCADE, related_name='resolution')
    datum = models.ManyToManyField(Datum, related_name='resolutions')
    points_for = models.IntegerField() # Represents the point value of the resolution based on total evaluation weight.
    points_against = models.IntegerField()
    certainty = models.IntegerField()
    false_count = models.IntegerField()
    confidence = models.FloatField() # 1 - (Total Points for Rejected Answers / Own Points)

    calculations = ResolutionManager()
    objects = models.Manager()


class Post(models.Model):
    """ A comment or description of activity pertaining to a survey question or answer"""
    researcher = models.ForeignKey(Researcher, on_delete=models.SET_NULL, null=True, blank=True, related_name='posts')
    question = models.ForeignKey('Survey.Question', on_delete=models.CASCADE, related_name='discussions', null=True)
    answer = models.ForeignKey('Survey.TextAnswer', on_delete=models.CASCADE, related_name='discussions', null=True)
    moment = models.DateTimeField(auto_now=True)
    action = models.CharField(max_length=748)
    comment = models.TextField(blank=True, null=True)

    def html(self):
        if self.moment.date() == datetime.today().date():
            time = "Today"
        elif self.moment.date() == datetime.today().date() - timedelta(days=1):
            time = "Yesterday"
        else:
            time = "on " + self.moment.strftime('%A, %b %d')

        html = "<div class='post-frame'>"
        html += "<span class='post-head'>{} {} {}</span>".format(
            self.researcher.name,
            self.action,
            time
        )
        if self.comment:
            html += "<p class='post-text'>{}</p>".format(self.comment)
        html += "</div>"
        return html


class Trace(models.Model):
    """ Records Evaluation Activity for Website """
    researcher = models.ForeignKey(Researcher, on_delete=models.SET_NULL, null=True, blank=True, related_name='traces')
    question = models.ForeignKey('Survey.Question', on_delete=models.SET_NULL, related_name='traces', null=True)
    answer = models.ForeignKey('Survey.TextAnswer', on_delete=models.SET_NULL, related_name='traces', null=True)
    evaluation = models.ForeignKey(Evaluation, on_delete=models.SET_NULL, related_name='traces', null=True)
    resolution = models.ForeignKey(Resolution, on_delete=models.SET_NULL, related_name='traces', null=True)
    data = models.ManyToManyField(Datum, related_name='traces')
    rscore = models.IntegerField()
    conf_x = models.IntegerField()
    moment = models.DateTimeField(auto_now_add=True)
    best_answer = models.CharField(max_length=128)
    best_answer_value = models.IntegerField()
    other_values = models.CharField(max_length=128)

Analyze/views.py
from django.http import HttpResponseRedirect
from django.db.models import Count
from django.shortcuts import redirect
from django.views.generic import TemplateView
from django.contrib.auth.mixins import UserPassesTestMixin

from Survey.models import Questionnaire, Question, TextAnswer
from .models import Datum, Note, Researcher, Post, Trace


class SurveySelectionView(UserPassesTestMixin, TemplateView):
    template_name = 'select_survey.html'

    def test_func(self):
        return self.request.user.is_researcher

    def surveys(self):
        researcher = Researcher.objects.get(user=self.request.user)
        print(researcher.eligible_for)
        return researcher.eligible_for.all()


class QuestionSelectionView(UserPassesTestMixin, TemplateView):
    template_name = 'select_question.html'

    def test_func(self):
        return self.request.user.is_researcher

    def survey(self):
        return Questionnaire.objects.get(id=self.kwargs.get('survey_id'))


class EvaluationView(UserPassesTestMixin, TemplateView):
    template_name = 'evaluation.html'

    def test_func(self):
        return self.request.user.is_researcher

    def dispatch(self, request, *args, **kwargs):
        if not self.answer():
            return redirect('Analyze:select_question', survey_id=self.kwargs.get('survey_id'))
        return super(EvaluationView, self).dispatch(request, *args, **kwargs)

    def question(self):
        return Question.objects.get(id=self.kwargs.get('question_id'))

    def answer(self):
        answer = TextAnswer.items.next_available_for_review_per_user(
            self.question(), Researcher.objects.get(user=self.request.user)
        )
        return answer

    def available_codes(self):
        return Datum.objects.filter(question=self.question()).annotate(count=Count('evaluations')).order_by('-count')

    def available_notes(self):
        return Note.objects.filter(question=self.question()).annotate(count=Count('evaluations')).order_by('-count')

    def discussion(self):
        posts = Post.objects.filter(question=self.question()).order_by('-moment')
        print(posts)
        html = ""
        for post in posts:
            html += post.html()
        return html


class GeneralActivityView(UserPassesTestMixin, TemplateView):
    template_name = 'records.html'

    def test_func(self):
        return self.request.user.is_admin

    def traces(self):
        return Trace.objects.all().order_by('-moment')[:100]


class UserActivityView(UserPassesTestMixin, TemplateView):
    template_name = 'records.html'

    def test_func(self):
        return self.request.user.is_admin

    def traces(self):
        return Trace.objects.filter(researcher=self.kwargs.get('slug')).order_by('-moment')[:100]


class AnswerActivityView(UserPassesTestMixin, TemplateView):
    template_name = 'records.html'

    def test_func(self):
        return self.request.user.is_admin

    def traces(self):
        return Trace.objects.filter(answer=self.kwargs.get('slug')).order_by('-moment')[:100]

Analyze/templates/evaluation.html
{% extends 'siteframe.html' %}
{% load static %}

{% block extra_css %}
    <link href="{% static 'css/evaluate.css' %}" rel="stylesheet">
{% endblock %}

{% block remove-top %}{% endblock %}

{% block lang_hooks %}
    <a href="{% url 'dashboard' %}" class="header_action text-white">My Dashboard</a> |
    <a href="{% url 'account_logout' %}" class="header_action text-white">Logout</a>
{% endblock %}
{% block overlay %}
<div id="overlay">
    <i class="fas fa-spinner fa-pulse"></i>
</div>
{% endblock %}
{% block main %}

    <p id="survey-title">{{ view.answer.question.questionnaire.label }}</p>

    <p id="question-text">{{ view.answer.question.text }}</p>

    <p id="answer-text">{{ view.answer.response }}</p>

    <hr>
    <div class="row">
        <div class="col-md-6 eval-left">

            <h5 class="field-label">Codes:</h5>
            <input id="addCode" type="text" placeholder="Create New Code">
            <a id="addCodeBtn" class="btn btn-dark add-btn hidden" data-question="{{ view.question.id }}">Add Code</a>
            <br>
            <hr>
            <ul id="codes" class="list-group">
                {% for code in view.available_codes %}
                    <li class="list-group-item" data-id="{{ code.id }}">{{ code.label }}</li>
                {% endfor %}
            </ul>


            <hr>


            <h5 class="field-label">Notes:</h5>
            <input id="addNote" type="text" placeholder="Create New Note">
            <a id="addNoteBtn" class="btn btn-dark add-btn hidden" data-question="{{ view.question.id }}">Add Note</a>
            <br>
            <hr>
            <ul id="notes" class="list-group">
                {% for note in view.available_notes %}
                    <li class="list-group-item" data-id="{{ note.id }}">{{ note.label }}</li>
                {% endfor %}
            </ul>

        </div>

        <div class="col-md-6 eval-right">
{#            <p> AI Suggestions </p>#}
{##}
{#            <div class="suggestion-box"></div>#}

            <div class="col-md-12 complete">
                <a id="skipBtn" style="margin: 40px 75px 40px 0px;" class="btn btn-light skip" data-answer="{{ view.answer.id }}">Skip</a>
                <a id="finishBtn" style="margin: 40px 0px;" class="btn btn-dark next disabled" data-answer="{{ view.answer.id }}">Finish</a>
            </div>

            <h5 class="field-label" style="margin-bottom:0">Discussion:</h5>
            <span class="select-discussion active" id="forQuestion" data-lookup="{{ view.answer.question.id }}">Question</span><span class="select-discussion" id="forAnswer" data-lookup="{{ view.answer.id }}">Answer</span>
            <hr>
            <ul id="discussion" class="list-group" style="height: 468px;">
                {% autoescape off %}{{ view.discussion }}{% endautoescape %}
            </ul>
            <a data-toggle="modal" data-target="#addPostModal" style="margin: 10px 15px 10px 0px;" class="btn btn-teal merge">Add Comment</a>
        </div>

    </div>
    {% if request.user.is_admin %}
    <div class="row">
        <div class="col-sm-12">
            <h4 style="margin-top: 24px">Mod Tools:</h4>
            <a id="mergeToggle" style="margin: 10px 15px 10px 0px;" class="btn btn-amber merge" data-answer="{{ view.answer.id }}">Merge Tool</a>
            <a id="removeToggle" style="margin: 10px 0px;" class="btn btn-red next delete" data-answer="{{ view.answer.id }}">Deletion Tool</a>
        </div>
    </div>
    {% endif %}

    <div class="modal fade" id="addPostModal" tabindex="-1" role="dialog" aria-labelledby="addPostModal" aria-hidden="true">
      <div class="modal-dialog" role="document">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="addPostModalLabel">Post to Discussion</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
              <span aria-hidden="true">&times;</span>
            </button>
          </div>
          <div class="modal-body" style="height: 300px;">
              <div class="form-group">
                <label for="mode">Pertains To:</label>
                <select class="form-control" id="mode">
                  <option value="forQuestion">This Question</option>
                  <option value="forAnswer">This Answer</option>
                </select>
              </div>
              <div class="form-group">
                 <label class="form-group-label" for="comment">Comment</label>
                  <textarea rows="6" class="form-control" id="comment"></textarea>
              </div>
          </div>
          <div class="modal-footer">
            <button type="button" class="btn btn-white btn-md" data-dismiss="modal">Close</button>
            <button type="button" class="btn btn-grey btn-md" data-dismiss="modal" id="postBtn" data-answer="{{ view.answer.id }}">Create</button>
          </div>
        </div>
      </div>
    </div>

{% endblock %}

{% block override_footer %}{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/evaluate.js' %}"></script>

    <script>
        $(function() {
            var availableCodes = [
                {% for code in view.codes %}
                    "{{ code }}",
                {% endfor %}
            ];
            $( "#tags" ).autocomplete({
              source: availableCodes
            });
        });
    </script>
{% endblock %}

Analyze/templates/records.html
{% extends 'siteframe.html' %}
{% load static %}

{% block extra_css %}
<style type="text/css" media="screen">

table td {
    padding: 7px;
}

.titles {
    background: whitesmoke;
}

</style>
{% endblock %}

{% block lang_hooks %}
    <a href="{% url 'dashboard' %}" class="header_action text-white">My Dashboard</a> |
    <a href="{% url 'account_logout' %}" class="header_action text-white">Logout</a>
{% endblock %}

{% block remove-top %}{% endblock %}
{% block main %}


    <h1 style="text-align: center; padding-top:30px">Analysis Records</h1>
        <div style="text-align: center;">
          <a href="/admin_tools/">Back to Admin Tools</a><br>
          <a style="color: rebeccapurple;" href="/analysis/records/">All Records</a>
        </div>
{#    <h4 class="mb-4">#}
{#        <strong>History</strong>#}
{#    </h4>#}
    <hr>
    <div class="traces">
    {% for trace in view.traces %}
        <div class="trace-frame">
            <p>
            <a href="{% url "Analyze:user-records" trace.researcher.id %}" class="name-link">{{ trace.researcher.name }}</a> submitted an evaluation for answer: <a href="{% url "Analyze:answer-records" trace.answer.id %}" class="name-link">{{ trace.answer.id }}</a> - {{ trace.answer.response }}<br>
            </p>
            <p>
                assigning the following codes: {% for datum in trace.data.all %}{{ datum.label }} ({{ datum.id }}) {% endfor %} <br>
            </p>
            <table>
                <thead>
                    <tr class="titles">
                        <td>Rschr weight</td>
                        <td>Question conf.</td>
                        <td>Best Answer (Value)</td>
                        <td>Other Answers</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            {{ trace.rscore }}
                        </td>
                        <td>
                            {{ trace.conf_x }}
                        </td>
                        <td>
                            {{ trace.best_answer}} ({{ trace.best_answer_value }})
                        </td>
                        <td>
                            {{ trace.other_values }}
                        </td>
                    </tr>
                </tbody>
            </table>

            <br>

            <br>

            {% if trace.resolution %}

                A RESOLUTION was applied:
                <table>
                <thead>
                    <tr class="titles">
                        <td>Pts For</td>
                        <td>Pts Against</td>
                        <td>Certainty</td>
                        <td>False Count</td>
                        <td>Confidence</td>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>
                            {{ trace.resolution.points_for }}
                        </td>
                        <td>
                            {{ trace.resolution.points_against }}
                        </td>
                        <td>
                            {{ trace.resolution.certainty}}
                        </td>
                        <td>
                            {{ trace.resolution.false_count }}
                        </td>
                        <td>
                            {{ trace.resolution.confidence }}
                        </td>
                    </tr>
                </tbody>
            </table>

                <br>

                <br>
            {% endif %}

        </div>
        <hr>
    {% endfor %}
    </div>


{% endblock %}

{% block override_footer %}
{% endblock %}

{% block extra_js %}
    <script>
        var researcher_accounts = {{ view.user_accounts|safe }};
    </script>
    <script>
    $(document).ready(function() {

    });
    </script>
{% endblock %}

Analyze/templates/select_question.html
{% extends 'siteframe.html' %}
{% load static %}
{% load analysis_tags %}
{% block remove-top %}{% endblock %}
{% block extra_css %}<link href="{% static 'css/backend.css' %}" rel="stylesheet">{% endblock %}


{% block lang_hooks %}
    <a href="{% url 'dashboard' %}" class="header_action text-white">My Dashboard</a>
    <a href="{% url 'account_logout' %}" class="header_action text-white">Logout</a>
{% endblock %}

{% block main %}

    <h1 style="text-align: center; padding-top:30px; border-bottom: 1px solid black;" id="surveyTitle" data-survey="{{ view.survey.id }}">{{ view.survey }}</h1>

    <div id="questionList">
{#    <div class="card question" id="intro">#}
{#          <div class="card-body">#}
{#              <div class="question-input">#}
{#                  <h4 class="title">Introduction</h4>#}
{#                  <p class="intro-text">{{ view.survey.introduction }}</p>#}
{#                  <a class="waves-effect waves-light btn btn-small yellow updateBtn" style="display: none"> Update</a>#}
{#              </div>#}
{#          </div>#}
{#    </div>#}
    {% for question in view.survey.question_set.all %}
        {% if question.has_eligible_answer %}
            {% has_available_answer question.id request.user as answer%}
            <div class="card question" id="{{ question.id }}">
              <div class="card-body">
                  <div class="question-input">
                      <p class="question-text">{{ question.text }}</p>

                      <a href="{% url "Analyze:evaluate" view.survey.id question.id %}"
                         class="waves-effect waves-light btn btn-small review updateBtn {% if not answer %}disabled{% endif %}"
                      >Review</a>
                 </div>
              </div>
            </div>
        {% endif %}
    {% endfor %}
    </div>


{##}
{#    <div class="card" id="createNew">#}
{#        <div class="card-header">#}
{#            + Add Question#}
{#        </div>#}
{#    </div>#}
{##}
{#    <div class="card" id="new" style="display: none">#}
{#          <div class="card-body">#}
{#              <div class="question-input">#}
{#                  <textarea onkeyup="auto_grow(this)" class="question-text" placeholder="Enter Question Text"></textarea>#}
{##}
{#                  <a class="waves-effect waves-light btn btn-small yellow updateBtn" style="display: none"> Submit</a>#}
{##}
{#                  <select class="form-control question-type">#}
{#                      <option value="" disabled selected>Select Question Type</option>#}
{#                      <option value="1" >Text Question</option>#}
{#                      <option value="2" >Boolean Question</option>#}
{#                      <option value="3" >Multiple Choice Question</option>#}
{#                      <option value="4" >Range Question</option>#}
{#                    </select>#}
{#             </div>#}
{#          </div>#}
{#    </div>#}
{##}
{#    <div class="builder-container">#}
{#          <a id="saveBtn" class="btn waves-effect waves-light btn-lg btn-dark builder-btn"><i class="far fa-save "></i> Save Survey</a>#}
{#    </div>#}

{% endblock %}

{% block override_footer %}
{% endblock %}

{% block extra_js %}
    <script type="text/javascript" src="{% static 'js/jquery-ui.min.js' %}"></script>
{#    <script type="text/javascript" src="{% static 'js/surveyBuilder.js' %}"></script>#}
{% endblock %}

Analyze/templates/select_survey.html
{% extends 'siteframe.html' %}
{% block remove-top %}{% endblock %}


{% block lang_hooks %}
    <a href="{% url 'dashboard' %}" class="header_action text-white">My Dashboard</a> |
    <a href="{% url 'account_logout' %}" class="header_action text-white">Logout</a>
{% endblock %}

{% block main %}

    <h1 style="text-align: center; padding-top:30px; border-bottom: 1px solid black">All Surveys</h1>
    {% for survey in view.surveys %}
        {% if survey.has_eligible_responses %}
            <div class="card">
              <div class="card-body">
                <h5 class="card-title">{{ survey.label }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ survey.date_opened }}</h6>
                <p class="card-text">{{ survey.description }}</p>
                <a href="{% url "Analyze:select_question" survey.id %}" class="card-link">Select Survey</a>
              </div>
            </div>
        {% endif %}
    {% endfor %}
{#    <hr>#}
{#    <h4 class="mb-4">#}
{#        <strong>Active</strong>#}
{#    </h4>#}
{#        {% for survey in view.current %}#}
{#        <div class="card">#}
{#          <div class="card-body">#}
{#            <h5 class="card-title">{{ survey.label }}</h5>#}
{#            <h6 class="card-subtitle mb-2 text-muted">{{ survey.date_opened }}</h6>#}
{#            <p class="card-text">{{ survey.description }}</p>#}
{#            <a href="{% url "survey_builder" survey.id %}" class="card-link">Edit Survey</a>#}
{#          </div>#}
{#        </div>#}
{#    {% endfor %}#}
{#    <hr>#}
{#    <h4 class="mb-4">#}
{#        <strong>Completed</strong>#}
{#    </h4>#}
{#        {% for survey in view.completed %}#}
{#        <div class="card">#}
{#          <div class="card-body">#}
{#            <h5 class="card-title">{{ survey.label }}</h5>#}
{#            <h6 class="card-subtitle mb-2 text-muted">{{ survey.date_opened }}</h6>#}
{#            <p class="card-text">{{ survey.description }}</p>#}
{#            <a href="{% url "survey_builder" survey.id %}" class="card-link">Edit Survey</a>#}
{#          </div>#}
{#        </div>#}
{#    {% endfor %}#}
{#    <hr>#}

{% endblock %}

{% block override_footer %}
{% endblock %}