Analyze/urls.py
from django.urls import path

from Analyze import views, actions

urlpatterns = [
    path('evaluate/select_survey', views.SurveySelectionView.as_view(), name='select_survey'),
    path('evaluate/<int:survey_id>', views.QuestionSelectionView.as_view(), name='select_question'),
    path('evaluate/<int:survey_id>/<int:question_id>', views.EvaluationView.as_view(), name='evaluate'),

    path('add_code/', actions.create_code),
    path('add_note/', actions.create_note),
    path('add_comment/', actions.add_comment),
    path('add_researcher/', actions.add_researcher),
    path('delete_tag/', actions.delete_tag),
    path('merge_tags/', actions.merge_tags),
    path('select_discussion/', actions.select_discussion),
    path('submit_evaluation/', actions.save_evaluation),
    path('records/user/<slug:slug>', views.UserActivityView.as_view(), name='user-records'),
    path('records/answer/<slug:slug>', views.AnswerActivityView.as_view(), name='answer-records'),
    path('records/', views.GeneralActivityView.as_view(), name='general-records'),
]

Blog/urls.py
from django.urls import path

from Blog import views

urlpatterns = [
    path('', views.RedirectToLatestPost.as_view(), name='latest_post'),
    path('create_post/', views.CreatePostView.as_view(), name='create_post'),
    path('drafts/', views.DraftsListView.as_view(), name='drafts'),
    path('edit_post/<slug:slug>', views.UpdatePostView.as_view(), name='edit_post'),
    path('index/', views.IndexView.as_view(), name='index'),
    path('<slug:slug>/', views.PostView.as_view(), name='view_post'),
]

Survey/urls.py
from django.urls import path

from Survey import views as views
from Survey import actions as actions

urlpatterns = [
    path('', views.SurveyAdminListView.as_view(), name="list"),

    path('manage/', views.ManageSurveysApp.as_view(), name="manage"),
    path('builder/<slug:slug>/', views.SurveyBuilderApp.as_view(), name='builder'),
    path('<slug:slug>/stats/', views.SurveyStatsView.as_view(), name='stats'),
    path('<slug:slug>/review/', views.SurveyAnswersView.as_view(), name="review"),
    path('<slug:slug>/review_weekly', views.WeeklyAnswersView.as_view(), name="review_weekly"),
    path('set_permissions/<slug:slug>/', views.ManageAnalysisPermissionsView.as_view(), name="analysis_permissions"),
    path('add_response/<slug:slug>/', views.AddResponseApp.as_view(), name='add_response'),

    path('survey_admin/', actions.survey_admin, name='admin'),
    path('preview_questionnaire/', actions.preview_questionnaire, name='preview_questionnaire'),
    path('save_survey', actions.save_questionnaire, name="save_survey"),
    path('accept_code/', actions.accept_code, name='accept_code'),

    path('get_question/', actions.get_question, name='get_question'),
    path('save_question/', actions.save_question, name="save_question"),
    path('delete_question/', actions.delete_question, name="delete_question"),
    path('move_question/', actions.move_question, name='move_question'),

    path('save_response/', actions.save_response, name="save_response"),
    path('process_manual_response', actions.process_manual_response, name='process_manual_response'),
    path('unlock_survey/', actions.unlock_survey_for_user, name="unlock"),
    path('create_weekly/', actions.create_weekly, name="create_weekly"),
    path('record_weekly/', actions.record_weekly, name="record_weekly"),

    path('auth_respondent/', actions.auth_respondent, name='auth_respondent'),
    path('log_out/', actions.log_out, name='log_out'),

    path('<slug:slug>/', views.TakeSurveyApp.as_view(), name="view"),
]

listen/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

from Home import views as views
from Home import actions as actions

from Project import views as projects_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('tinymce/', include('tinymce.urls')),

    path('newsletter/', include('newsletter.urls')),
    path('surveys/', include(('Survey.urls', 'Survey'), namespace="Surveys")),
    path('blog/', include(('Blog.urls', "Blog"), namespace="Blog")),
    path('projects/', include(('Project.urls', "Project"), namespace="Project")),
    path('analysis/', include(('Analyze.urls', 'Analyze'), namespace='Analyze')),
    path('contacts/', include(('Contacts.urls', 'Contacts'), namespace='Contacts')),

    path('admin_tools/', views.AdminToolsView.as_view(), name="admin_tools"),

    path('accounts/login/', views.ListenLoginView.as_view(), name='account_login'),
    path('accounts/logout/', views.logout_request, name='account_logout'),
    path('accounts/signup/', views.ListenSignupView.as_view(), name='account_signup'),
    path('accounts/', include('django.contrib.auth.urls')),

    path('', views.HomePageView.as_view()),
    path('contribute/', views.DonateView.as_view(), name='donate'),
    path('dashboard/', views.DashboardView.as_view(), name="dashboard"),
    path('snapcode/', views.SnapcodeView.as_view(), name='snapcode'),
    path('news/', views.NewsView.as_view(), name='news'),

    path('newsletter_builder/<slug:slug>/', views.NewsletterBuilderView.as_view(), name='newsletter_builder'),
    path('read_newsletter/<slug:slug>/', views.ViewNewsletter.as_view(), name='view_newsletter'),
    path('newsletters/', views.NewsletterListView.as_view(), name='newsletter_list'),
    path('modify_newsletter/', actions.modify_newsletter, name='modify_newsletter'),

    path('submit_secret/', actions.submit_secret),
    path('set_permissions/', actions.set_permissions),
    path('quick_signup/', actions.quick_signup, name='quick_signup'),

    path('email_copy/', TemplateView.as_view(template_name='email_copy.html'), name='email'),


    path('about/', views.AboutView.as_view(), name="about"),
    path('start_survey/', views.SurveyLandingPage.as_view(), name="survey_landing"),
    path('home/', views.HomePageView.as_view(), name="home"),
    path('staff/', views.StaffPanelView.as_view(), name='staff'),

    path('i18n/', include('django.conf.urls.i18n')),
    path('', views.HomePageView.as_view()),

    path('sample/', projects_views.SampleProjectView.as_view(), name='sample'),
    path('<slug:slug>/', projects_views.ProjectView.as_view(), name='project'),
]

Survey/forms.py
from django.forms import ModelForm, CharField

from Survey.models import TextAnswer, BooleanAnswer, ChoiceAnswer, RangeAnswer, Respondent, WeeklyAnswer, Question
from Survey.choices import SHORT_TEXT, LONG_TEXT, BOOLEAN, CHOICE, RANGE, MULTI


class QuestionForm(ModelForm):
    options = CharField(required=False)
    translations = CharField(required=False)

    class Meta:
        model = Question
        fields = ['questionnaire', 'text', 'response_format']


class TextAnswerForm(ModelForm):
    class Meta:
        model = TextAnswer
        fields = ['response']


class BooleanAnswerForm(ModelForm):
    class Meta:
        model = BooleanAnswer
        fields = ['response']


class ChoiceAnswerForm(ModelForm):
    class Meta:
        model = ChoiceAnswer
        fields = ['response']


class RangeAnswerForm(ModelForm):
    class Meta:
        model = RangeAnswer
        fields = ['response']


class RespondentDemographicsForm(ModelForm):
    class Meta:
        model = Respondent
        fields = ['heritage', 'gender', 'date_of_birth']


class WeeklyAnswerForm(ModelForm):
    class Meta:
        model = WeeklyAnswer
        fields = ['text']


RESPONSE_FORMS = {
    SHORT_TEXT: TextAnswerForm,
    LONG_TEXT: TextAnswerForm,
    BOOLEAN: BooleanAnswerForm,
    CHOICE: ChoiceAnswerForm,
    RANGE: RangeAnswerForm,
    MULTI: ChoiceAnswerForm,
}

Survey/views.py
import uuid

from json import dumps as to_json
from datetime import datetime

from django.core.serializers.json import DjangoJSONEncoder
from django.views.generic import TemplateView, FormView
from django.views.generic.edit import DeleteView
from django.urls import reverse_lazy

from django.contrib.auth.mixins import UserPassesTestMixin

from Home.models import Organization
from Home.views import LanguageMixin
from Project.models import Project
from Analyze.models import Researcher
from .models import Questionnaire, Respondent, WeeklyQuestion, TextAnswer, Translation
from .choices import RESPONSE_FORMATS
from Survey import structs


class TakeSurveyApp(UserPassesTestMixin, TemplateView):
    template_name = 'survey_app.html'
    app_name = "survey"

    def test_func(self):
        authorized = True
        slug = self.kwargs.get('slug')
        survey = Questionnaire.objects.get(slug=slug)
        if survey.is_closed() or survey.hidden:
            authorized = False
        elif survey.login_is_required:
            if self.request.user.is_authenticated:
                respondent = Respondent.objects.get(user=self.request.user)
                authorized = respondent.eligible_for.filter(id=survey.id).exists()
            else:
                authorized = False
        else:
            if self.request.user.is_authenticated:
                respondent = Respondent.objects.get(user=self.request.user)
                respondent.eligible_for.add(survey)
            else:
                key = self.request.session.session_key
                self.request.session['key'] = key
        return authorized

    def survey_data(self):
        slug = self.kwargs.get('slug')
        survey = Questionnaire.objects.get(slug=slug)
        questions = survey.question_set.all()
        language_code = self.request.LANGUAGE_CODE
        text_translations = {}
        options_translations = {}
        answers = {}
        if self.request.LANGUAGE_CODE == 'en':
            intro = survey.introduction
        else:
            intro = Translation.objects.filter(questionnaire=survey, language__code=language_code).first().text

        for question in questions:

            translation_set = question.translation_set.all().select_related('language')
            for t in translation_set:
                text_translations[question.id] = {t.language.code: t.text}
                if t.options:
                    options_translations[question.id] = {t.language.code: t.options}

            if self.request.user.is_authenticated:
                answers[question.id] = question.get_user_response(self.request.user)
            else:
                session_key = self.request.session.session_key
                answers[question.id] = question.get_anonymous_response(session_key)

        data = {
            "slug": slug,
            "intro": intro,
            "questions": list(questions.values('response_format', 'text', 'options', 'id')),
            "textTranslations": text_translations,
            "optionsTranslations": options_translations,
            "answers": answers
        }
        return to_json(data)


class ManageSurveysApp(UserPassesTestMixin, TemplateView):
    template_name = "manage_app.html"
    app_name = "manageSurveys"

    def test_func(self):
        user = self.request.user
        return True if user.is_admin or user.is_staff else False

    def all_surveys(self):
        data = {
            'past': to_json(list(Questionnaire.available.in_the_past().values(
                'pk', 'label', 'date_opened', 'date_closed', 'slug'
            )), cls=DjangoJSONEncoder),
            'present': to_json(list(Questionnaire.available.today().values(
                'pk', 'label', 'date_opened', 'date_closed', 'slug'
            )), cls=DjangoJSONEncoder),
            'future': to_json(list(Questionnaire.available.in_the_future().values(
                'pk', 'label', 'date_opened', 'date_closed', 'slug'
            )), cls=DjangoJSONEncoder),
        }
        return data


class AddResponseApp(UserPassesTestMixin, TemplateView):
    template_name = "add_response_app.html"
    app_name = "addResponse"

    def test_func(self):
        user = self.request.user
        return True if user.is_admin or user.is_staff else False

    def get_context_data(self, *args, **kwargs):
        context = super(AddResponseApp, self).get_context_data(*args, **kwargs)
        slug = self.kwargs.get('slug')
        questions = Questionnaire.objects.get(slug=slug).question_set.all()
        questions = list(questions.values('response_format', 'text', 'options', 'id'))
        for question in questions:
            if 'text' in question['response_format']:
                question['response'] = []
                question['proposed'] = ""
            elif question['response_format'] == 'select_multi':
                question['response'] = []
            elif question['response_format'] == 'range':
                question['response'] = 50
            else:
                question['response'] = None
        context['questions'] = to_json(questions)
        return context


class SurveyBuilderApp(UserPassesTestMixin, TemplateView):
    template_name = "builder_app.html"
    app_name = "editSurvey"

    def test_func(self):
        user = self.request.user
        return True if user.is_admin or user.is_staff else False

    def get_context_data(self, *args, **kwargs):
        context = super(SurveyBuilderApp, self).get_context_data(*args, **kwargs)
        slug = self.kwargs.get('slug')

        if slug == 'new':
            data = structs.QUESTIONNAIRE
            questions = {}
        else:
            survey = Questionnaire.objects.get(slug=slug)
            data = survey.builder_data()
            question_objs = survey.question_set.all()
            questions = []
            for obj in question_objs:
                questions.append({
                    'pk': obj.id,
                    'text': obj.text,
                    'response_format': obj.get_response_format_display()
                })
        data['slug'] = slug

        context['surveyData'] = to_json(data, cls=DjangoJSONEncoder)
        context['questions'] = questions
        context['response_options'] = {opt: label for opt, label in RESPONSE_FORMATS}
        context['organization'] = Organization.objects.get(name="Listen To Shafter").id

        return context


class SurveyAdminListView(UserPassesTestMixin, LanguageMixin, TemplateView):
    template_name = "questionnaire_list.html"

    def test_func(self):
        permitted = False
        if self.request.user.is_admin or self.request.user.is_staff:
            permitted = True
        return permitted

    @property
    def organization(self):
        return self.request.user.organization

    def unpublished(self):
        return Questionnaire.available.in_the_future().filter(organization=self.organization)

    def current(self):
        return Questionnaire.available.today().filter(organization=self.organization)

    def completed(self):
        return Questionnaire.available.in_the_past().filter(organization=self.organization)

    def weekly_questions(self):
        return WeeklyQuestion.objects.filter(organization=self.request.user.organization).order_by('-week_of')

    def newsletter_date(self):
        return datetime.today().strftime('%B-%Y').lower()

    def projects(self):
        return Project.objects.filter(organization=self.request.user.organization)


class SurveyStatsView(UserPassesTestMixin, TemplateView):
    template_name = 'survey_stats.html'

    def test_func(self):
        permitted = False
        if self.request.user.is_admin or self.request.user.is_staff:
            permitted = True
        return permitted

    def survey(self):
        return Questionnaire.objects.get(id=self.kwargs.get('pk'))

    def all_responses(self):
        survey = self.survey()
        return TextAnswer.items.count_users_responded_between(survey, survey.date_opened, datetime.now())

    def all_completions(self):
        survey = self.survey()
        return TextAnswer.items.count_users_finished_between(survey, survey.date_opened, datetime.now())


class SurveyBuilderView(UserPassesTestMixin, LanguageMixin, TemplateView):
    template_name = "survey_builder.html"
    hide_options = [1, 2, 4]

    def survey(self):
        return Questionnaire.objects.get(id=self.kwargs.get('pk'))

    def test_func(self):
        user = self.request.user
        permitted = False
        if user.is_admin or (user.is_staff and user.organization == self.survey().organization):
            permitted = True
        return permitted


class SurveyAnswersView(UserPassesTestMixin, LanguageMixin, TemplateView):
    template_name = "answers.html"

    def survey(self):
        return Questionnaire.objects.get(id=self.kwargs.get('pk'))

    def test_func(self):
        user = self.request.user
        permitted = False
        if user.is_admin or (user.is_staff and user.organization == self.survey().organization):
            if not self.survey().qualitative:
                permitted = True
        return permitted


class WeeklyAnswersView(UserPassesTestMixin, TemplateView):
    template_name = "weekly_answers.html"

    def question(self):
        return WeeklyQuestion.objects.get(id=self.kwargs.get('pk'))

    def answers(self):
        return self.question().weeklyanswer_set.all().order_by('-id')

    def test_func(self):
        user = self.request.user
        permitted = False
        if user.is_admin or (user.is_staff and user.organization) == self.question().organization:
            permitted = True
        return permitted


def activate_survey(request):
    survey = Questionnaire.objects.get(id=request.POST.get('pk')).delete()
    survey.date_opened = datetime.today()
    survey.closed = False


class DeleteSurveyView(DeleteView):
    model = Questionnaire
    success_url = reverse_lazy('Surveys:survey_list')

Survey/templates/add_response_app.html
{% extends 'vueframe.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}
{% load i18n %}
{% render_bundle 'chunk-vendors' %}
{% render_bundle 'addResponse' %}

{% block pageTitle %}Add Response{% endblock %}

{% block appName %}addResponse{% endblock %}


{% block rootData %}
<script>
    rootData.questions = {{ questions|safe }}
    rootData.responseOptions = {{ response_options|safe }}
    rootData.organization = {{ organization|safe }}
    rootData.urlpaths = {
        manageSurveys: '{% url 'Surveys:manage' %}',
        addResponse: '{% url 'Surveys:process_manual_response' %}',
        ...rootData.urlpaths
    }
</script>
{% endblock %}

Survey/templates/builder_app.html
{% extends 'vueframe.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}
{% load i18n %}
{% render_bundle 'chunk-vendors' %}
{% render_bundle 'builder' %}

{% block pageTitle %}Survey Builder{% endblock %}

{% block appName %}builderApp{% endblock %}


{% block rootData %}
<script>
    rootData.surveyData = {{ surveyData|safe }}
    rootData.questions = {{ questions|safe }}
    rootData.responseOptions = {{ response_options|safe }}
    rootData.organization = {{ organization|safe }}
    rootData.urlpaths = {
        submitSurveyForm:'{% url 'Surveys:save_survey' %}',
        submitQuestionForm: '{% url 'Surveys:save_question' %}',
        fetchQuestionData: '{% url 'Surveys:get_question' %}',
        deleteQuestion: '{% url 'Surveys:delete_question' %}',
        moveQuestion: '{% url 'Surveys:move_question' %}',
        ...rootData.urlpaths
    }
</script>
{% endblock %}

Survey/templates/dashboard.html
{% extends 'siteframe_static.html' %}
{% load static %}
{% load home_tags %}
{% load i18n %}

{% block stylesheets %}
<style>
    input[type=text], input[type=email] {
        border: 1px solid gray;
        padding: 4px;
    }
</style>
{% endblock %}

{% block content %}
<div class="flex flex-col gap-6 items-center bg-gray-100" style="min-height: calc(100vh - 296px);">
    <div class="flex flex-col lg:w-2/3 bg-white px-16 py-8 h-full">

        <h1 class="text-3xl pb-2 border-b mb-2 text-center">{% translate "My Dashboard" %}</h1>
        {% if request.user.is_admin %}
        <div style="text-align: center;">
             <a style="color: darkred; font-weight: 800;" href="/admin_tools/">Admin Tools</a>
        </div>
        {% endif %}
        {% if request.user.is_researcher %}
        <div style="text-align: center;">
             <a style="color: #9e00a7;font-weight: 800;" href="{% url 'Analyze:select_survey' %}">Researcher Portal</a>
        </div>
        {% endif %}

        <div class="flex flex-col gap-12 my-12 select-none">
            {% if view.new_surveys %}
            <div class="flex flex-col gap-3">
                <h4 class="text-2xl font-title border-b pb-2">
                    <strong>{% translate "New Surveys" %}</strong>
                </h4>
                <div class="flex flex-col gap-8 ">
                {% for survey in view.new_surveys %}
                    <a href="{% url "Surveys:view" survey.slug %}" class="card cursor-pointer hover:bg-gray-100 border shadow rounded p-4">
                        <h5 class="border-b mb-1 pb-1 font-bold">{{ survey|translate_label:language }}</h5>
                        {% if view.get_language == 1 %}
                        {% language 'es' %}
                        <h6 class="text-sm text-gray-500">{{ survey.date_opened | date}}</h6>
                        {% endlanguage %}
                        {% else %}
                        <h6 class="text-sm text-gray-500">{{ survey.date_opened }}</h6>
                        {% endif %}
                        <p class="text-sm">{{ survey.description }}</p>
                    </a>
                {% endfor %}
                </div>
                <div class="flex flex-col justify-center gap-2 p-4 pb-6 border shadow text-center bg-gray-300">
                    <p class="">
                        {% blocktrans %}
                            Enter Survey Access Code:
                        {% endblocktrans %}
                    </p>
                    <div class="flex flex-row justify-center items-center">
                        <input type="text" class="border focus:outline-none p-1 text-gray-700 h-10">
                        <button class="items-center px-3 flex flex-row gap-2 text-white h-10" style="background: #728f98;">
                            {% translate 'Enter' %}
                            <svg class="w-6 h-6" fill="currentColor" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M10.293 15.707a1 1 0 010-1.414L14.586 10l-4.293-4.293a1 1 0 111.414-1.414l5 5a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0z" clip-rule="evenodd"></path><path fill-rule="evenodd" d="M4.293 15.707a1 1 0 010-1.414L8.586 10 4.293 5.707a1 1 0 011.414-1.414l5 5a1 1 0 010 1.414l-5 5a1 1 0 01-1.414 0z" clip-rule="evenodd"></path></svg>
                        </button>
                    </div>
                </div>
            </div>
            {% endif %}
            {% if view.started %}
            <div class="flex flex-col gap-3">
                <h4 class="text-2xl font-title border-b pb-2">
                     <strong>{% translate "Surveys In Progress" %}</strong>
                </h4>
                {% for survey in view.started %}
                <a href="{% url "Surveys:view" survey.slug %}" class="card cursor-pointer hover:bg-gray-100 border shadow rounded p-4">
                    <h5 class="border-b mb-1 pb-1 font-bold">{{ survey|translate_label:language }}</h5>
                    {% if view.get_language == 1 %}
                    {% language 'es' %}
                    <h6 class="text-sm text-gray-500">{{ survey.date_opened | date}}</h6>
                    {% endlanguage %}
                    {% else %}
                    <h6 class="text-sm text-gray-500">{{ survey.date_opened }}</h6>
                    {% endif %}
                    <p class="text-sm">{{ survey.description }}</p>
                </a>
                {% endfor %}
            </div>
            {% endif %}
            {% if view.finished %}
            <div class="flex flex-col gap-3">
                <h4 class="text-2xl font-title border-b pb-2">
                     <strong>{% translate "Completed Surveys" %}</strong>
                </h4>
                {% for survey in view.finished %}
                <a href="{% url "Surveys:view" survey.slug %}" class="card cursor-pointer hover:bg-gray-100 border shadow rounded p-4">
                    <h5 class="border-b mb-1 pb-1 font-bold">{{ survey|translate_label:language }}</h5>
                    {% if view.get_language == 1 %}
                    {% language 'es' %}
                    <h6 class="text-sm text-gray-500">{{ survey.date_opened | date}}</h6>
                    {% endlanguage %}
                    {% else %}
                    <h6 class="text-sm text-gray-500">{{ survey.date_opened }}</h6>
                    {% endif %}
                    <p class="text-sm">{{ survey.description }}</p>
                </a>
                {% endfor %}
            </div>
        {% endif %}
        </div>
{#        <hr>#}
{#        <h4 class="mb-4"><strong>{% translate "Settings" %}</strong></h4>#}
{#        <form method="POST" class="flex flex-col gap-4">#}
{#            {% csrf_token %}#}
{#            {% if form.errors %}#}
{#                {% for field in form %}#}
{#                    {% for error in field.errors %}#}
{#                        <div class="alert alert-danger">#}
{#                            <strong>{{ error|escape }}</strong>#}
{#                        </div>#}
{#                    {% endfor %}#}
{#                {% endfor %}#}
{#                {% for error in form.non_field_errors %}#}
{#                    <div class="alert alert-danger">#}
{#                        <strong>{{ error|escape }}</strong>#}
{#                    </div>#}
{#                {% endfor %}#}
{#            {% endif %}#}
{#         {{ form.as_p }}#}
    {#    <input id="allows_contact_email" name="allows_contact_email" type="checkbox">#}
    {#    <label for="allowsEmail">Allow Contact via Email</label><br>#}
    {#    <input id="allowsSMS" name="allows_contact_sms" type="checkbox">#}
    {#    <label for="allowsSMS">Allow Contact via Text/SMS</label><br>#}
    {#    <label for="email">My Email:</label><br>#}
    {#    <input type="text" id="email" name="email" value="{{ request.user.email }}"><br>#}
    {#    <label for="phone">My Phone Number:</label><br>#}
    {#    <input type="text" id="phone" name="phone_number" value="{{ request.user.formatted_phone_number }}"><br>#}
{#        <div class="flex flex-row justify-center">#}
{#            <input type="submit" class="btn btn-dark submit cursor-pointer hover:text-gray-100" value="{% translate "Save Settings" %}">#}
{#        </div>#}
{#        </form>#}

    </div>
</div>
{% endblock %}

{% block extra_js %}
    <script>
    $(function() {
        $('#unlockReveal').click(function() {
            $(this).hide();
            $('#unlockFrame').show();
        });

        $('#unlockBtn').click(function(){
            $.ajax({
                url: "/surveys/unlock_survey/",
                type: "POST",
                dataType: 'json',
                data: {'code': $('#unlock').val()},
                success: function (result) {
                    if (result.success === true) {
                        window.location.reload()
                    } else {
                        $('#unlockMsg').text(result.message).show()
                    }
                }
            });
        });
    })
    </script>
{% endblock %}

Survey/templates/manage_app.html
{% extends 'vueframe.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}
{% load i18n %}
{% render_bundle 'chunk-vendors' %}
{% render_bundle 'manageSurveys' %}

{% block pageTitle %}Survey Manager{% endblock %}

{% block appName %}managerApp{% endblock %}

{% block rootData %}
<script>
rootData.surveys = {{ view.all_surveys|safe }}
rootData.urlpaths.previewSurvey = "{% url "Surveys:preview_questionnaire" %}"
</script>
{% endblock %}

Survey/templates/survey_app.html
{% extends 'vueframe.html' %}
{% load static %}
{% load render_bundle from webpack_loader %}
{% load i18n %}
{% render_bundle 'chunk-vendors' %}
{% render_bundle 'survey' %}

{% block css %}
<link href="{% static 'css/slanted_button.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
{% endblock %}

{% block pageTitle %}Surveys{% endblock %}

{% block appName %}surveyApp{% endblock %}


{% block rootData %}
<script>
    rootData.surveyData = {{ view.survey_data|safe }}
    {% if request.user.is_authenticated %}
        rootData.user = {
            'username': '{{request.user.username}}'
        }
    {% else %}
        rootData.user = {}
    {% endif %}

    rootData.urlpaths.dashboard = {% url 'dashboard' %}
    rootData.urlpaths.submitResponse = '{% url 'Surveys:save_response' %}'
    rootData.urlpaths.submitAuthForm = '{% url 'Surveys:auth_respondent' %}'
    rootData.urlpaths.signOut = '{% url 'Surveys:log_out' %}'

    {% get_current_language as LANGUAGE_CODE %}
    rootData.language = '{{ LANGUAGE_CODE }}'
    {% if LANGUAGE_CODE == 'en' %}
        rootData.languageForm = '<form id="languageForm" method="post" action="{% url 'set_language' %}">{% csrf_token %}<input style="display: none" value="es" name="language"><button  id="langSwitch" class="skew-button" data-location="site"><span>Participar en español.</span></button></form>'
    {% endif %}

    {% if LANGUAGE_CODE == 'es' %}
        rootData.languageForm = '<form id="languageForm" method="post" action="{% url 'set_language' %}">{% csrf_token %}<input style="display: none" value="en" name="language"><button id="langSwitch" type="submit" class="skew-button" data-location="site"><span>Participate in English</span></button></form>'
    {% endif %}

</script>
{% endblock %}